# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='longbeachopportunity',
            options={'verbose_name': 'Opportunity', 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AddField(
            model_name='longbeachopportunity',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
