# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_auto_20160714_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='longbeachopportunity',
            name='benefit_type',
            field=models.CharField(blank=True, choices=[('money', 'money'), ('advice', 'advice')], max_length=8, verbose_name='benefit type'),
        ),
    ]
