# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0003_longbeachopportunity_benefit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='longbeachopportunity',
            name='value_prop',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
