# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0004_longbeachopportunity_value_prop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longbeachopportunity',
            name='benefit_type',
        ),
    ]
